names = ['beijing','xian','chengdu','dali','Maldives']
# print(sorted(names))
# print(sorted(names, reverse=True))
# print(names)
# names.reverse()
# print(names)
# names.reverse()
# # print(names)
# names.sort()
# print(names)
names.sort(reverse=True)
print(names)
print(len(names))